services:
  nextjs-app: # Assuming you renamed the service to nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
      # --- ADD THESE LINES ---
      # Pass environment variables from your host (which get loaded from .env.prod)
      # as build arguments to the Dockerfile's build stage.
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
      # --- END ADDITIONS ---
    ports:
      - "3000:3000"
    environment:
      # Keep these for runtime access to all variables (especially non-NEXT_PUBLIC_ ones)
      # and for server-side code that might access NEXT_PUBLIC_ variables directly
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    env_file:
      - .env.prod # This ensures all variables are available at runtime
