export enum Pages {
  SIGN_IN = "/users/sign-in",
  SIGN_UP = "/users/sign-up",
  RESET_PASSWORD = "/users/reset-password",
  UPDATE_PASSWORD = "/users/update-password",
  DASHBOARD = "/dashboard",
  PLANTS = "/plants",
  PLANTS_NEW_OCR = "/plants/new/ocr",
  PLANTS_NEW_AI = "/plants/new/ai",
  PLANTS_NEW_IMPORT = "/plants/new/import",
  MEMBERS = "/members",
  APPROVALS = "/approvals",
  PROFILE = "/profile",
  SUPPORT = "/support",
  ORGANIZATIONS = "/organizations",
}
