import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Digital Herbarium",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <nav className="fixed bg-white p-5 py-4 border-b w-screen">
        <div className="max-w-6xl mx-auto">
          <Image src="/asm-logo.png" alt="ASM Logo" width={70} height={30} />
        </div>
      </nav>
      <main className="py-24 px-10 flex-1 bg-[#F9FAFB]">
        <div className="max-w-6xl mx-auto">{children}</div>
      </main>
    </>
  );
}
